services:
  - digital_sales:
      url: http://0.0.0.0:8007/openapi.json
      description: This Digital Sales Skills API provides sales professionals with a unified interface to access territory accounts, retrieve client information from TPP, manage job roles, and synchronize contacts between Zoominfo and Salesloftâ€”streamlining the process of managing customer relationships and sales data across multiple platforms.
mcpServers:
  filesystem:
    url: http://localhost:8112/sse
    description: Standard file system operations for workspace management
  email:
    url: http://localhost:8000/sse
    description: standard email server connected to the user's email.